### ISSUE TITLE
ARK Launcher - File Browser: Fasten directory loading times

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#171] opened 2023-06-29 21:09 UTC
### New Feature

**Tweak loading times to browse directories with a larger amount of isos**

When putting a larger amount of isos in a directory, loading of this directory takes quite some time. I think in some way files are processed (meta data?). Here are some examples:

Entering a directory of isos (270): 40 sec
Entering a directory of (empty) files (270): 38 sec
Entering a directory of (empty) directories (270): 5 sec

Since it should be just a listing of items regardless of its type, shouldnt it be equally fast?

**Comment by JoseAaronLopezGarcia** [comment] 2023-06-29 21:14
I'll look into it.

**Comment by svensvond** [comment] 2023-06-29 22:09
looks to me if its related to getFileSize() which is only executed for files. (unsigned BrowserFile::getFileSize(){ ?)
I dont care about the file size on the psp itself actually, faster loading times would weight much more.

**Comment by JoseAaronLopezGarcia** [comment] 2023-07-06 09:35
Closing as duplicate of https://github.com/PSP-Archive/ARK-4/issues/178

**Closed by JoseAaronLopezGarcia** 2023-07-06 09:35 UTC
Labels: Feature Request
